#lang racket

(define double
  (lambda (f)
    (lambda (x)
      (f (f x)))))

(define inc (lambda (x) (+ x 1)))

(((double (double double)) inc) 5)
;
; (double double) => 4*
; (double ...) = > 4* => 16
; 21

(((double (lambda (x)
            (double (double x)))) inc) 5)

(((lambda (x)
    ((lambda (x)
       (double (double x)))
     ((lambda (x)
        (double (double x)))
      x))) inc) 5)


(((lambda (x)
    ((lambda (x)
       (double (double x)))
     ((lambda (x)
        (double (double x)))
      x))) inc) 5)

(((lambda (x)
    (double (double x)))
  ((lambda (x)
     (double (double x)))
   inc))
 5)

(((lambda (x)
    (double (double x)))
  (double (double inc)))
 5)

((double (double (double (double inc))))
 5)

((double (double (double (lambda (x) (inc (inc x))))))
 5)

((double
  (double
   (lambda (x)
     ((lambda (x) (inc (inc x)))
      ((lambda (x) (inc (inc x)))
       x)))))
 5)

((double
  (lambda (x)
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     ((lambda (x)
        ((lambda (x) (inc (inc x)))
         ((lambda (x) (inc (inc x)))
          x)))
      x))))
 5)

((lambda (x)
   ((lambda (x)
      ((lambda (x)
         ((lambda (x) (inc (inc x)))
          ((lambda (x) (inc (inc x)))
           x)))
       ((lambda (x)
          ((lambda (x) (inc (inc x)))
           ((lambda (x) (inc (inc x)))
            x)))
        x)))
    ((lambda (x)
       ((lambda (x)
          ((lambda (x) (inc (inc x)))
           ((lambda (x) (inc (inc x)))
            x)))
        ((lambda (x)
           ((lambda (x) (inc (inc x)))
            ((lambda (x) (inc (inc x)))
             x)))
         x)))
     x)))
 5)

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     ((lambda (x)
        ((lambda (x) (inc (inc x)))
         ((lambda (x) (inc (inc x)))
          x)))
      x)))
  5))

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  ((lambda (x)
     ((lambda (x) (inc (inc x)))
      ((lambda (x) (inc (inc x)))
       x)))
   5)))


((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  ((lambda (x) (inc (inc x)))
   ((lambda (x) (inc (inc x)))
    5))))


((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  ((lambda (x) (inc (inc x)))
   (inc (inc 5)))))
       

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  ((lambda (x) (inc (inc x)))
   7)))


((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  (inc (inc 7))))


((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  9))

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x) (inc (inc x)))
  ((lambda (x) (inc (inc x)))
   9)))


((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x) (inc (inc x)))
  (inc (inc 9))))

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 ((lambda (x) (inc (inc x)))
  11))

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 (inc (inc 11)))

((lambda (x)
   ((lambda (x)
      ((lambda (x) (inc (inc x)))
       ((lambda (x) (inc (inc x)))
        x)))
    ((lambda (x)
       ((lambda (x) (inc (inc x)))
        ((lambda (x) (inc (inc x)))
         x)))
     x)))
 13)

((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 ((lambda (x)
    ((lambda (x) (inc (inc x)))
     ((lambda (x) (inc (inc x)))
      x)))
  13))

((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 ((lambda (x) (inc (inc x)))
  ((lambda (x) (inc (inc x)))
   13)))


((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 ((lambda (x) (inc (inc x)))
  (inc (inc 13))))


((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 ((lambda (x) (inc (inc x)))
  15))

((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 (inc (inc 15)))
     
((lambda (x)
   ((lambda (x) (inc (inc x)))
    ((lambda (x) (inc (inc x)))
     x)))
 17)
    
((lambda (x) (inc (inc x)))
 ((lambda (x) (inc (inc x)))
  17))

((lambda (x) (inc (inc x)))
 (inc (inc 17)))

((lambda (x) (inc (inc x)))
 19)

(inc (inc 19))

21